# Site settings
title: Ramble On 
email: cas653@gmail.com
description: "A travel report for all - the causal tourist, cultural chameleon or the travel-junkie youngster (that's me)- with stories, itineraries and helpful hints for along the way. The time is now: eat, sleep, Ramble the world."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
